version: '3'
services:
  aci2swatch:
    #container_name: aci2swatch_objects
    image: b0066365/aci2fmc:v0.1
    restart: always
    volumes:
    #- .:/mnt/scripts/swatch
    - ./log/:/home/app/log
    - .:/home/app/data
    - .:/home/app/src
    command: python /home/app/src/aci2swatch.py
